### ISSUE TITLE
The deployed module doesn't seem to follow current nodejs conventions

### ISSUE THREAD

**Issue by julienw** [mstange/gecko-profiler-demangle#1]
See https://github.com/benmosher/eslint-plugin-import/issues/2098#issuecomment-848338645 for more insight.

**Comment by ljharb** [comment]
Specifically, if you want the package to be requireable/importable, you need to specify "main" and "exports".

**Comment by mstange** [comment]
This module was produced by wasm-pack, and I think I even filed this very bug at some point: https://github.com/rustwasm/wasm-pack/issues/94
Maybe I never repackaged after the fix. I'll try that.

**Comment by mstange** [comment]
Updating the dependencies and building with `wasm-pack build --out-name index` fixes this. I'm currently testing the output and will release a new version soon.

**Comment by mstange** [comment]
@ljharb I've published 0.3.0 with the main file now being named `index.js`. The package.json still doesn't specify any "exports" and I'm not sure what's meant by that - I don't see an "exports" key on [these package.json docs](https://docs.npmjs.com/cli/v7/configuring-npm/package-json).
Is the new version at https://unpkg.com/browse/gecko-profiler-demangle@0.3.0/ correct or does it need more changes?

**Comment by ljharb** [comment]
You don't really need the "exports" field here, because in this case there's only one .js file in the package.

It looks fine to me, but it really should include `"main": "./index.js"` to be explicit.

**Comment by mstange** [comment]
Thanks for the feedback! I filed https://github.com/rustwasm/wasm-pack/issues/1009 on that. However, given the current maintainership status of wasm-pack, it probably won't see any action any time soon. I'll adjust the package.json manually in the meantime.

**Comment by mstange** [comment]
Ok, fixed in https://unpkg.com/browse/gecko-profiler-demangle@0.3.1/ .

**Comment by julienw** [comment]
Thanks for the quick update @mstange :-)
