### ISSUE TITLE
The published version doesn't work properly

### ISSUE THREAD

**Issue by julienw** [mstange/gecko-profiler-demangle#2]
See https://unpkg.com/browse/gecko-profiler-demangle@0.3.2/index.js.
The line:
```js
export * from "./index_bg.js";
```
breaks with
```
Module not found: Error: Can't resolve './index_bg.js' in '/home/circleci/project/node_modules/gecko-profiler-demangle'
```
Indeed, there's no `index_bg.js` (see https://unpkg.com/browse/gecko-profiler-demangle@0.3.2/)...

Any idea what's causing this @mstange ?

**Comment by mstange** [comment]
Oops.

**Comment by mstange** [comment]
This was fixed in https://github.com/rustwasm/wasm-pack/pull/839 but no release was made since that fix. I will work around it manually.

**Comment by mstange** [comment]
@julienw Can you try again?

**Comment by julienw** [comment]
> @julienw Can you try again?

Sorry, I forgot about that. But I could try again today when depfu proposed me the update, and now everything seems to work fine :-)

**Comment by mstange** [comment]
great!
